name: movie_booking
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  
  fluttertoast: ^8.2.4
  shared_preferences: ^2.2.2
  flutter_paypal_checkout: ^1.0.1
  flutter_inappwebview: ^5.8.0
  carousel_slider: ^4.2.1
  flutter_secure_storage: ^9.0.0
  http: ^0.13.6
  expandable_text: 2.3.0
  flutter_launcher_icons: "^0.11.0"
  gap: ^3.0.1
  intl: ^0.17.0
  flutter_native_splash: ^1.2.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  qr_flutter: ^4.1.0
  scroll_snap_list: ^0.9.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

fonts:
  - family: Roboto
    fonts:
      - asset: assets/fonts/RobotoBold.ttf
        weight: 700
      - asset: assets/fonts/RobotoRegular.ttf
        weight: 400
  - family: Poppins
    fonts:
      - asset: assets/fonts/PoppinsRegular.ttf
        weight: 400

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/ic_launcher.png"
